### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_root'

### ISSUE THREAD

**Issue by rafaeltiveron** [jaredsampson/pymolprobity#10]
I've installed PyMOLProbity. But, when I load plugin, I receive this:

```
Traceback (most recent call last):
  File "/root/pymol/lib/python2.7/site-packages/pmg_tk/startup/pymolprobity/__init__.py", line 51, in <lambda>
    command = lambda s=self: gui.PyMOLProbity(s))
  File "/root/pymol/lib/python2.7/site-packages/pmg_tk/startup/pymolprobity/gui.py", line 526, in __init__
    mpobj = tk.StringVar()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 344, in __init__
    Variable.__init__(self, master, value, name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 244, in __init__
    self._root = master._root()
AttributeError: 'NoneType' object has no attribute '_root'
Exception AttributeError: "StringVar instance has no attribute '_tk'" in <bound method StringVar.__del__ of <Tkinter.StringVar instance at 0x7f3774e25248>> ignored
```

What is the problem?

**Comment by jaredsampson** [comment]
What version of PyMOL are you using?

**Comment by rafaeltiveron** [comment]
PyMOL 2.1.0

**Comment by rafaeltiveron** [comment]
Sorry, I installed v1.2 from "Release" tab. When I installed from "master-zip", it worked.

**Comment by jaredsampson** [comment]
Ok, glad to hear it.  Although I suppose that means I should bump the version to avoid that problem.  Thanks for mentioning it.
